### PR TITLE
fix: Update items-fallback.js for the Knightfall patch

### PR DESCRIPTION
**Pull request by madvac**
update items fallback file to current patch

### CODE REVIEW

**Comment by matheussampaio** [comment]
Hey there, thanks for the patch. Can you commit following conventional commits so the auto release picks it up?

**Comment by madvac** [comment]
well...i am "new" here (my first pull request)
I found this https://www.conventionalcommits.org/en/v1.0.0/

do i need make a new commit?..  or can i "update" this commit?

**Comment by matheussampaio** [comment]
No problem ,I can help with that.

1. Update the commit title (look for `git commit --amend` to help you with that). Change the commit's title to `fix: Update items-fallback.js for the Knightfall patch`.
2. Push the new commit to your branch with `git push` (similar to what you did on the first time). This time around, it will be required to use `--force` to overwrite the commit with the wrong title.

**Comment by matheussampaio** [comment]
If you're using the online editor (not using `git` manually on your machine), it will be a different process... 

The important thing here is to change the commit title from `Update items-fallback.js` to `fix: Update items-fallback.js for the Knightfall patch`.

**Review by matheussampaio — CHANGES_REQUESTED** [review]
Let's rename the commit's title and I can merge the changes. Thanks!

**Comment by madvac** [comment]
i think i make somthing wrong.
i change commit title.
But also i make some merge remote-tracking (i tried to revert last commit, but nothing changed).

**Comment by matheussampaio** [comment]
Thanks! I’ll review later today and merge.

**Comment by madvac** [comment]
Thanks for helping me...next time i will try to make it correctly.

**Review by matheussampaio — APPROVED** [review]

**Pull request merged**
